"""merchants transactions events

Revision ID: 267e2361befe
Revises: 
Create Date: 2026-04-25 11:47:02.945030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '267e2361befe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchants',
    sa.Column('merchant_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('merchant_id')
    )
    op.create_table('transactions',
    sa.Column('transaction_id', sa.String(length=64), nullable=False),
    sa.Column('merchant_id', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('payment_status', sa.String(length=32), server_default=sa.text("'none'"), nullable=False),
    sa.Column('settlement_status', sa.String(length=32), server_default=sa.text("'none'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_event_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.merchant_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_index('ix_transactions_merchant_payment', 'transactions', ['merchant_id', 'payment_status'], unique=False)
    op.create_index('ix_transactions_merchant_updated', 'transactions', ['merchant_id', 'updated_at'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('transaction_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.transaction_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_index('ix_events_transaction_occurred', 'events', ['transaction_id', 'occurred_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_events_transaction_occurred', table_name='events')
    op.drop_table('events')
    op.drop_index('ix_transactions_merchant_updated', table_name='transactions')
    op.drop_index('ix_transactions_merchant_payment', table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('merchants')
    # ### end Alembic commands ###
